name: Snyk Vulnerability Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Snyk_oss_scan:
    name: Snyk OSS Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
      - name: Run Snyk Code and OSS to check for vulnerabilities
        run: |
          npx snyk code test --severity-threshold=high
          npx snyk test --severity-threshold=critical --fail-on=upgradable
